name: flutter_tcg_calculator
description: A TCG probabilty calculator utilizing Flutter, Riverpod and Firebase
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  dev: ^1.0.0
  firebase_core: ^2.15.0
  firebase_ui_firestore: ^1.5.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^10.0.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.4.0
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true